apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "portfolio.fullname" . }}-backend
  labels:
    {{- include "portfolio.backend.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.backend.replicaCount }}

  selector:
    matchLabels:
      {{- include "portfolio.backend.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "portfolio.backend.selectorLabels" . | nindent 8 }}

    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: backend

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.backend.service.targetPort }}
              protocol: TCP

          envFrom:
            - configMapRef:
                name: {{ include "portfolio.fullname" . }}-backend-config

            - secretRef:
                name: {{ include "portfolio.fullname" . }}-backend-secret

          livenessProbe:
            httpGet:
              path: {{ .Values.backend.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.backend.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.livenessProbe.periodSeconds }}

          readinessProbe:
            httpGet:
              path: {{ .Values.backend.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.backend.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.backend.readinessProbe.periodSeconds }}

          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
