apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "portfolio.fullname" . }}-backend-config
  labels:
    {{- include "portfolio.backend.labels" . | nindent 4 }}

data:
  DATABASE_URL: "postgresql://{{ .Values.postgres.username }}:{{ .Values.postgres.password }}@{{ include "portfolio.fullname" . }}-postgres:{{ .Values.postgres.service.port }}/{{ .Values.postgres.database }}"
  ALGORITHM: "{{ .Values.backend.config.algorithm }}"
  ACCESS_TOKEN_EXPIRE_MINUTES: "{{ .Values.backend.config.accessTokenExpireMinutes }}"
