apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "portfolio.fullname" . }}-frontend
  labels:
    {{- include "portfolio.frontend.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.frontend.replicaCount }}

  selector:
    matchLabels:
      {{- include "portfolio.frontend.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "portfolio.frontend.selectorLabels" . | nindent 8 }}

    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: frontend

          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP

          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
