apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "portfolio.fullname" . }}-postgres-pvc
  labels:
    {{- include "portfolio.postgres.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.postgres.persistence.accessMode }}
  resources:
    requests:
      storage: {{ .Values.postgres.persistence.size }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
