apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "portfolio.fullname" . }}-reverse-proxy
  labels:
    {{- include "portfolio.reverseproxy.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.reverseProxy.replicaCount }}

  selector:
    matchLabels:
      {{- include "portfolio.reverseproxy.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "portfolio.reverseproxy.selectorLabels" . | nindent 8 }}

    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      containers:
        - name: reverse-proxy

          image: "{{ .Values.reverseProxy.image.repository }}:{{ .Values.reverseProxy.image.tag }}"
          imagePullPolicy: {{ .Values.reverseProxy.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.reverseProxy.service.targetPort }}
              protocol: TCP

          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf

          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            {{- toYaml .Values.reverseProxy.resources | nindent 12 }}

      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "portfolio.fullname" . }}-reverse-proxy-config

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
